version: 2
jobs:
  build_and_deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.9
    branches:
        only:
          - master
    steps:
      - checkout

      - run:
          name: install now
          command: yarn global add now

      - run:
          name: deploy asap now!!
          command: |
            now --public -t ${ZEIT_TOKEN}
            now alias -t

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_and_deploy
